export const WEBHOOK_TOPICS = {
	ACCOUNT: 'account',
	PROPERTY: 'property',
	RESERVATION: 'reservation',
	BOOKING: 'booking',
	COMPANY: 'company',
	GROUP: 'group',
	BLOCK: 'block',
	UNIT: 'unit',
	UNITGROUP: 'unitgroup',
	UNITATTRIBUTEDEFINITION: 'unitattributedefinition',
	FOLIO: 'folio',
	INVOICE: 'invoice',
	RATEPLAN: 'rateplan',
	NIGHTAUDIT: 'nightaudit',
	MAINTENANCE: 'maintenance',
	CITYTAX: 'citytax',
	SERVICE: 'service',
	PAYMENTTRANSACTION: 'paymenttransaction',
};

export const WEBHOOK_EVENTS = {
	[WEBHOOK_TOPICS.ACCOUNT]: {
		SET_TO_LIVE: 'set-to-live',
		SUSPENDED: 'suspended',
	},
	[WEBHOOK_TOPICS.PROPERTY]: {
		CREATED: 'created',
		CHANGED: 'changed',
		SET_TO_LIVE: 'set-to-live',
		ARCHIVED: 'archived',
		DELETED: 'deleted',
	},
	[WEBHOOK_TOPICS.RESERVATION]: {
		CREATED: 'created',
		AMENDED: 'amended',
		CHANGED: 'changed',
		CHECKED_IN: 'checked-in',
		CHECKED_OUT: 'checked-out',
		CHECK_IN_REVERTED: 'check-in-reverted',
		SET_TO_NO_SHOW: 'set-to-no-show',
		UNIT_ASSIGNED: 'unit-assigned',
		UNIT_UNASSIGNED: 'unit-unassigned',
		PAYMENT_ACCOUNT_SET: 'payment-account-set',
		PAYMENT_ACCOUNT_REMOVED: 'payment-account-removed',
		CANCELED: 'canceled',
		DELETED: 'deleted',
	},
	[WEBHOOK_TOPICS.BOOKING]: {
		CREATED: 'created',
		CHANGED: 'changed',
		DELETED: 'deleted',
	},
	[WEBHOOK_TOPICS.COMPANY]: {
		CREATED: 'created',
		CHANGED: 'changed',
		DELETED: 'deleted',
	},
	[WEBHOOK_TOPICS.GROUP]: {
		CREATED: 'created',
		CHANGED: 'changed',
		DELETED: 'deleted',
	},
	[WEBHOOK_TOPICS.BLOCK]: {
		CREATED: 'created',
		CHANGED: 'changed',
		DELETED: 'deleted',
		CONFIRMED: 'confirmed',
		RELEASED: 'released',
		WASHED: 'washed',
		CANCELLED: 'cancelled',
	},
	[WEBHOOK_TOPICS.UNIT]: {
		CREATED: 'created',
		CHANGED: 'changed',
		DELETED: 'deleted',
	},
	[WEBHOOK_TOPICS.UNITGROUP]: {
		CREATED: 'created',
		CHANGED: 'changed',
		DELETED: 'deleted',
	},
	[WEBHOOK_TOPICS.UNITATTRIBUTEDEFINITION]: {
		CREATED: 'created',
		CHANGED: 'changed',
		DELETED: 'deleted',
	},
	[WEBHOOK_TOPICS.FOLIO]: {
		CREATED: 'created',
		CLOSED: 'closed',
		BALANCE_CHANGED: 'balance-changed',
		REOPENED: 'reopened',
		DELETED: 'deleted',
		CHARGES_CHANGED: 'charges-changed',
		CHARGE_POSTED: 'charge-posted',
		DEBITOR_CHANGED: 'debitor-changed',
		TRANSITORY_CHARGE_POSTED: 'transitory-charge-posted',
		ALLOWANCE_POSTED: 'allowance-posted',
		DEPOSIT_ITEM_ADDED: 'deposit-item-added',
		DEPOSIT_ITEM_CHANGED: 'deposit-item-changed',
		DEPOSIT_ITEM_DELETED: 'deposit-item-deleted',
		PAYMENT_ADDED: 'payment-added',
		PAYMENT_POSTED: 'payment-posted',
		PAYMENT_FAILED: 'payment-failed',
		PAYMENT_CANCELED: 'payment-canceled',
		REFUND_ADDED: 'refund-added',
		REFUND_POSTED: 'refund-posted',
		REFUND_FAILED: 'refund-failed',
		CHARGE_MOVED_FROM_FOLIO: 'charge-moved-from-folio',
		TRANSITORY_CHARGE_MOVED_FROM_FOLIO: 'transitory-charge-moved-from-folio',
		PAYMENT_MOVED_FROM_FOLIO: 'payment-moved-from-folio',
		REFUND_MOVED_FROM_FOLIO: 'refund-moved-from-folio',
		CHARGE_MOVED_TO_FOLIO: 'charge-moved-to-folio',
		TRANSITORY_CHARGE_MOVED_TO_FOLIO: 'transitory-charge-moved-to-folio',
		PAYMENT_MOVED_TO_FOLIO: 'payment-moved-to-folio',
		REFUND_MOVED_TO_FOLIO: 'refund-moved-to-folio',
		ALLOWANCE_MOVED_TO_FOLIO: 'allowance-moved-to-folio',
		ALLOWANCE_MOVED_FROM_FOLIO: 'allowance-moved-from-folio',
	},
	[WEBHOOK_TOPICS.INVOICE]: {
		CREATED: 'created',
		CANCELED: 'canceled',
		PAID: 'paid',
		WRITTEN_OFF: 'written-off',
		SIGNED: 'signed',
		RENDERED: 'rendered',
	},
	[WEBHOOK_TOPICS.RATEPLAN]: {
		CREATED: 'created',
		CHANGED: 'changed',
		DELETED: 'deleted',
	},
	[WEBHOOK_TOPICS.NIGHTAUDIT]: {
		STARTED: 'started',
		SUCCEEDED: 'succeeded',
		FAILED: 'failed',
	},
	[WEBHOOK_TOPICS.MAINTENANCE]: {
		CREATED: 'created',
		CHANGED: 'changed',
		DELETED: 'deleted',
	},
	[WEBHOOK_TOPICS.CITYTAX]: {
		CREATED: 'created',
		CHANGED: 'changed',
		DELETED: 'deleted',
	},
	[WEBHOOK_TOPICS.SERVICE]: {
		CREATED: 'created',
		CHANGED: 'changed',
		DELETED: 'deleted',
	},
	[WEBHOOK_TOPICS.PAYMENTTRANSACTION]: {
		AUTHORIZED: 'authorized',
		REFUSED: 'refused',
		AUTHORIZATION_ADJUSTED: 'authorization-adjusted',
		CANCELLED: 'cancelled',
		CANCELLATION_DENIED: 'cancellation-denied',
		SENT_FOR_SETTLE: 'sent-for-settle',
		CAPTURE_DENIED: 'capture-denied',
		SENT_FOR_SETTLE_REVERSED: 'sent-for-settle-reversed',
		SENT_FOR_REFUND: 'sent-for-refund',
		REFUND_DENIED: 'refund-denied',
		REFUNDED: 'refunded',
		SENT_FOR_REFUND_REVERSED: 'sent-for-refund-reversed',
		REFUND_REVERSED: 'refund-reversed',
		SETTLED: 'settled',
		DISPUTE_OPENED: 'dispute-opened',
		DISPUTE_INFORMATION_REQUESTED: 'dispute-information-requested',
		DISPUTE_INFORMATION_SUPPLIED: 'dispute-information-supplied',
		FRAUD_DETECTED: 'fraud-detected',
		DISPUTE_LOST: 'dispute-lost',
		DISPUTE_WON: 'dispute-won',
		SETTLED_ON_MERCHANT_ACCOUNT: 'settled-on-merchant-account',
		REFUNDED_FROM_MERCHANT_ACCOUNT: 'refunded-from-merchant-account',
		CHARGED_BACK: 'charged-back',
		CHARGED_BACK_FROM_MERCHANT_ACCOUNT: 'charged-back-from-merchant-account',
		CHARGEBACK_REVERSED: 'chargeback-reversed',
		CHARGEBACK_REVERSED_ON_MERCHANT_ACCOUNT: 'chargeback-reversed-on-merchant-account',
		SECOND_TIME_CHARGED_BACK: 'second-time-charged-back',
		SECOND_TIME_CHARGED_BACK_FROM_MERCHANT_ACCOUNT:
			'second-time-charged-back-from-merchant-account',
	},
};

// Account-level events that should not be filtered by propertyIds
export const ACCOUNT_LEVEL_EVENTS = [
	{ topic: WEBHOOK_TOPICS.ACCOUNT, event: WEBHOOK_EVENTS[WEBHOOK_TOPICS.ACCOUNT].SET_TO_LIVE },
	{ topic: WEBHOOK_TOPICS.ACCOUNT, event: WEBHOOK_EVENTS[WEBHOOK_TOPICS.ACCOUNT].SUSPENDED },
	{ topic: WEBHOOK_TOPICS.PROPERTY, event: WEBHOOK_EVENTS[WEBHOOK_TOPICS.PROPERTY].CREATED },
	{ topic: WEBHOOK_TOPICS.BOOKING, event: WEBHOOK_EVENTS[WEBHOOK_TOPICS.BOOKING].CREATED },
	{ topic: WEBHOOK_TOPICS.BOOKING, event: WEBHOOK_EVENTS[WEBHOOK_TOPICS.BOOKING].CHANGED },
	{ topic: WEBHOOK_TOPICS.BOOKING, event: WEBHOOK_EVENTS[WEBHOOK_TOPICS.BOOKING].DELETED },
];

export const WEBHOOK_BASE_URL = 'https://webhook.apaleo-staging.com/v1';
