import { INodeProperties } from 'n8n-workflow';

export const operationOptions: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['availability-v1'], resource: ['Availability'] } },
		options: [
			{
				name: 'Get Available Services',
				value: 'AvailabilityServicesGet',
				action: 'Get available services',
				description: 'Get a list of all available services in a property',
			},
			{
				name: 'Get Available Unit Groups',
				value: 'AvailabilityUnit-groupsGet',
				action: 'Get available unit groups',
				description: 'Get a list of all available unit groups in a property',
			},
			{
				name: 'Get Available Units',
				value: 'AvailabilityUnitsGet',
				action: 'Get available units',
				description: 'Get a list of all available units in a property',
			},
			{
				name: 'Update Unit Group Availability',
				value: 'AvailabilityUnit-groupsByIdPatch',
				action: 'Update unit group availability',
				description: 'Allows to modify the unit group availability',
			},
		],
		default: 'AvailabilityServicesGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['availability-v1'], resource: ['ReservationAvailability'] } },
		options: [
			{
				name: 'Get Available Units For Reservation',
				value: 'AvailabilityReservationsByIdUnitsGet',
				action: 'Get available units for reservation',
				description: 'Get a list of all available units for a reservation',
			},
		],
		default: 'AvailabilityReservationsByIdUnitsGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['booking-v1'], resource: ['Block'] } },
		options: [
			{
				name: 'Count Blocks',
				value: 'BookingBlocks$countGet',
				action: 'Count blocks',
				description: 'Returns number of blocks',
			},
			{
				name: 'Create Block',
				value: 'BookingBlocksPost',
				action: 'Create block',
				description: 'Creates a block',
			},
			{
				name: 'Get Block',
				value: 'BookingBlocksByIdGet',
				action: 'Get block',
				description: 'Returns a specific block',
			},
			{
				name: 'List Blocks',
				value: 'BookingBlocksGet',
				action: 'List blocks',
				description: 'Returns a list of blocks',
			},
		],
		default: 'BookingBlocks$countGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['booking-v1'], resource: ['BlockActions'] } },
		options: [
			{
				name: 'Amend Block',
				value: 'BookingBlock-actionsByIdAmendPut',
				action: 'Amend block',
				description: 'Allow to modify a block',
			},
			{
				name: 'Cancel Block',
				value: 'BookingBlock-actionsByIdCancelPut',
				action: 'Cancel block',
				description: 'Cancel a block',
			},
			{
				name: 'Confirm Block',
				value: 'BookingBlock-actionsByIdConfirmPut',
				action: 'Confirm block',
				description: 'Confirm a block',
			},
			{
				name: 'Release Block',
				value: 'BookingBlock-actionsByIdReleasePut',
				action: 'Release block',
				description: 'Release a block',
			},
			{
				name: 'Wash Block',
				value: 'BookingBlock-actionsByIdWashPut',
				action: 'Wash block',
				description: 'Wash a block',
			},
		],
		default: 'BookingBlock-actionsByIdAmendPut',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['booking-v1'], resource: ['Booking'] } },
		options: [
			{
				name: 'Add Reservation To Booking',
				value: 'BookingBookingsByIdReservationsPost',
				action: 'Add reservation to booking',
				description: 'Add one or multiple reservations to an existing booking',
			},
			{
				name: 'Add Reservation To Booking Force',
				value: 'BookingBookingsByIdReservations$forcePost',
				action: 'Add reservation to booking force',
				description: 'Add one or multiple reservations to an existing booking regardless of availability or restrictions',
			},
			{
				name: 'Create Booking',
				value: 'BookingBookingsPost',
				action: 'Create booking',
				description: 'Creates a booking for one or more reservations',
			},
			{
				name: 'Create Booking Force',
				value: 'BookingBookings$forcePost',
				action: 'Create booking force',
				description: 'Creates a booking for one or more reservations regardless of availability or restrictions',
			},
			{
				name: 'Get Booking',
				value: 'BookingBookingsByIdGet',
				action: 'Get booking',
				description: 'Returns a specific booking',
			},
			{
				name: 'List Bookings',
				value: 'BookingBookingsGet',
				action: 'List bookings',
				description: 'Returns a list of all bookings, filtered by the specified parameters',
			},
			{
				name: 'Update Booking',
				value: 'BookingBookingsByIdPatch',
				action: 'Update booking',
				description: 'Allows to modify certain booking properties',
			},
		],
		default: 'BookingBookingsByIdReservationsPost',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['booking-v1'], resource: ['Group'] } },
		options: [
			{
				name: 'Add Reservation To Group',
				value: 'BookingGroupsByIdReservationsPost',
				action: 'Add reservation to group',
				description: 'Add one or multiple reservations to an existing group booking using blocked inventory',
			},
			{
				name: 'Create Group',
				value: 'BookingGroupsPost',
				action: 'Create group',
				description: 'Creates a group booking',
			},
			{
				name: 'Get Group',
				value: 'BookingGroupsByIdGet',
				action: 'Get group',
				description: 'Returns a specific group booking',
			},
			{
				name: 'List Groups',
				value: 'BookingGroupsGet',
				action: 'List groups',
				description: 'Returns a list of all group bookings, filtered by the specified parameters',
			},
			{
				name: 'Update Group',
				value: 'BookingGroupsByIdPatch',
				action: 'Update group',
				description: 'Allows to modify certain group booking properties',
			},
		],
		default: 'BookingGroupsByIdReservationsPost',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['booking-v1'], resource: ['Offer'] } },
		options: [
			{
				name: 'List Offer Index',
				value: 'BookingOffer-indexGet',
				action: 'List offer index',
				description: 'Returns offers with rates and availabilities for the specified range',
			},
			{
				name: 'List Offers',
				value: 'BookingOffersGet',
				action: 'List offers',
				description: 'Returns offers for one specific stay',
			},
			{
				name: 'List Rate Plan Offers',
				value: 'BookingRate-plan-offersGet',
				action: 'List rate plan offers',
				description: 'Returns offers for a specific rate plan',
			},
			{
				name: 'List Service Offers',
				value: 'BookingService-offersGet',
				action: 'List service offers',
				description: 'Returns service offers for one specific stay',
			},
		],
		default: 'BookingOffer-indexGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['booking-v1'], resource: ['Reservation'] } },
		options: [
			{
				name: 'Count Reservations',
				value: 'BookingReservations$countGet',
				action: 'Count reservations',
				description: 'Returns the number of reservations fulfilling the criteria specified in the parameters',
			},
			{
				name: 'Get Reservation',
				value: 'BookingReservationsByIdGet',
				action: 'Get reservation',
				description: 'Returns a specific reservation',
			},
			{
				name: 'Get Reservation Offers',
				value: 'BookingReservationsByIdOffersGet',
				action: 'Get reservation offers',
				description: 'Returns offers for one specific reservation',
			},
			{
				name: 'Get Reservation Service Offers',
				value: 'BookingReservationsByIdService-offersGet',
				action: 'Get reservation service offers',
				description: 'Returns service offers for one specific reservation',
			},
			{
				name: 'Get Reservation Services',
				value: 'BookingReservationsByIdServicesGet',
				action: 'Get reservation services',
				description: 'Returns the services booked for a specific reservation',
			},
			{
				name: 'List Reservations',
				value: 'BookingReservationsGet',
				action: 'List reservations',
				description: 'Returns a list of all reservations, filtered by the specified parameters',
			},
			{
				name: 'Remove Service From Reservation',
				value: 'BookingReservationsByIdServicesDelete',
				action: 'Remove service from reservation',
				description: 'Removes a service from a reservation',
			},
			{
				name: 'Update Reservation',
				value: 'BookingReservationsByIdPatch',
				action: 'Update reservation',
				description: 'Allows to modify certain reservation properties',
			},
		],
		default: 'BookingReservations$countGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['booking-v1'], resource: ['ReservationActions'] } },
		options: [
			{
				name: 'Add City Tax',
				value: 'BookingReservation-actionsByIdAdd-city-taxPut',
				action: 'Add city tax',
				description: 'Adds the city tax to a reservation',
			},
			{
				name: 'Amend Reservation',
				value: 'BookingReservation-actionsByIdAmendPut',
				action: 'Amend reservation',
				description: 'Allows you to amend the stay details of a reservation',
			},
			{
				name: 'Amend Reservation Force',
				value: 'BookingReservation-actionsByIdAmend$forcePut',
				action: 'Amend reservation force',
				description: 'Allows you to amend the stay details of a reservation regardless of availability or restrictions',
			},
			{
				name: 'Assign Specific Unit',
				value: 'BookingReservation-actionsByIdAssign-unitByUnitIdPut',
				action: 'Assign specific unit',
				description: 'Assign a specific unit to a reservation',
			},
			{
				name: 'Assign Unit',
				value: 'BookingReservation-actionsByIdAssign-unitPut',
				action: 'Assign unit',
				description: 'Assign a unit to a reservation',
			},
			{
				name: 'Book Service',
				value: 'BookingReservation-actionsByIdBook-servicePut',
				action: 'Book service',
				description: 'Book the service for a specific reservation',
			},
			{
				name: 'Book Service Force',
				value: 'BookingReservation-actionsByIdBook-service$forcePut',
				action: 'Book service force',
				description: 'Book the service for a specific reservation regardless of availability',
			},
			{
				name: 'Cancel Reservation',
				value: 'BookingReservation-actionsByIdCancelPut',
				action: 'Cancel reservation',
				description: 'Cancel a reservation',
			},
			{
				name: 'Check In',
				value: 'BookingReservation-actionsByIdCheckinPut',
				action: 'Check in',
				description: 'Check-in of a reservation',
			},
			{
				name: 'Check Out',
				value: 'BookingReservation-actionsByIdCheckoutPut',
				action: 'Check out',
				description: 'Check-out of a reservation',
			},
			{
				name: 'Mark No Show',
				value: 'BookingReservation-actionsByIdNoshowPut',
				action: 'Mark no show',
				description: 'Set a reservation to No-show',
			},
			{
				name: 'Remove City Tax',
				value: 'BookingReservation-actionsByIdRemove-city-taxPut',
				action: 'Remove city tax',
				description: 'Removes the city tax from a reservation',
			},
			{
				name: 'Revert Check In',
				value: 'BookingReservation-actionsByIdRevert-checkinPut',
				action: 'Revert check in',
				description: 'Reverses the check-in of a reservation',
			},
			{
				name: 'Unassign Units',
				value: 'BookingReservation-actionsByIdUnassign-unitsPut',
				action: 'Unassign units',
				description: 'Unassign units from a reservation',
			},
		],
		default: 'BookingReservation-actionsByIdAdd-city-taxPut',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['booking-v1'], resource: ['Types'] } },
		options: [
			{
				name: 'List Allowed Values',
				value: 'BookingTypesByTypeAllowed-valuesGet',
				action: 'List allowed values',
				description: 'Returns a list of values that a field of the specified type can take in the specified country',
			},
			{
				name: 'List Sources',
				value: 'BookingTypesSourcesGet',
				action: 'List sources',
				description: 'Returns a list of supported sources',
			},
		],
		default: 'BookingTypesByTypeAllowed-valuesGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['finance-v1'], resource: ['Folio'] } },
		options: [
			{
				name: 'Check Folio Exists',
				value: 'FinanceFoliosByIdHead',
				action: 'Check folio exists',
				description: 'Check if the folio exists',
			},
			{
				name: 'Count Folios',
				value: 'FinanceFolios$countGet',
				action: 'Count folios',
				description: 'Returns number of folios',
			},
			{
				name: 'Create Folio',
				value: 'FinanceFoliosPost',
				action: 'Create folio',
				description: 'Create additional folios for a reservation, or new external folios',
			},
			{
				name: 'Get Folio',
				value: 'FinanceFoliosByIdGet',
				action: 'Get folio',
				description: 'Returns one folio',
			},
			{
				name: 'List Folios',
				value: 'FinanceFoliosGet',
				action: 'List folios',
				description: 'Returns a list of all folios',
			},
			{
				name: 'Update Folio',
				value: 'FinanceFoliosByIdPatch',
				action: 'Update folio',
				description: 'Allows to modify certain properties of a folio',
			},
		],
		default: 'FinanceFoliosByIdHead',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['finance-v1'], resource: ['FolioActions'] } },
		options: [
			{
				name: 'Bulk Move Charges',
				value: 'FinanceFolio-actionsBulk-movePut',
				action: 'Bulk move charges',
				description:
					'Move multiple charges from one folio to another. Multiple source folios and multiple target folios can be specified.',
			},
			{
				name: 'Close Folio',
				value: 'FinanceFolio-actionsByFolioIdClosePut',
				action: 'Close folio',
				description: 'Closes a folio',
			},
			{
				name: 'Correct Folio',
				value: 'FinanceFolio-actionsByFolioIdCorrectPost',
				action: 'Correct folio',
				description:
					'Corrects a folio by moving some charges. This operation creates a new folio with the charges from the request. The payment, equal to the sum of charges, is also split to this new folio so that both folios will have 0 balance.',
			},
			{
				name: 'Create Bulk Allowances',
				value: 'FinanceFolio-actionsByFolioIdBulk-allowancesPost',
				action: 'Create bulk allowances',
				description: 'Posts allowances for a folio',
			},
			{
				name: 'Create Charge Allowance',
				value: 'FinanceFolio-actionsByFolioIdChargesByChargeIdAllowancesPost',
				action: 'Create charge allowance',
				description: 'Posts an allowance for a charge',
			},
			{
				name: 'Create Folio Allowance',
				value: 'FinanceFolio-actionsByFolioIdAllowancesPost',
				action: 'Create folio allowance',
				description: 'Posts an allowance for a folio',
			},
			{
				name: 'Create Folio Cancellation Fee',
				value: 'FinanceFolio-actionsByFolioIdCancellation-feePost',
				action: 'Create folio cancellation fee',
				description:
					'Adds and directly posts a cancellation fee to the folio. If there are any fees configured for the property, an additional charge for each configured fee will be added. If a routing instruction is defined for the cancellation fee service type, the fee will be moved to the destination folio.',
			},
			{
				name: 'Create Folio Charge',
				value: 'FinanceFolio-actionsByFolioIdChargesPost',
				action: 'Create folio charge',
				description:
					'Adds and directly posts a charge to the folio. If there are any fees configured for the property, an additional charge for each configured fee will be added.',
			},
			{
				name: 'Create Folio No Show Fee',
				value: 'FinanceFolio-actionsByFolioIdNo-show-feePost',
				action: 'Create folio no show fee',
				description:
					'Adds and directly posts a no-show fee to the folio. If there are any fees configured for the property, an additional charge for each configured fee will be added. If a routing instruction is defined for the no-show fee service type, the fee will be moved to the destination folio.',
			},
			{
				name: 'Create Folio Transitory Charge',
				value: 'FinanceFolio-actionsByFolioIdTransitory-chargesPost',
				action: 'Create folio transitory charge',
				description:
					'Adds and directly posts a transitory charge to the folio. If there are any fees configured for the property, an additional charge for each configured fee will be added.',
			},
			{
				name: 'Move All Folio Charges',
				value: 'FinanceFolio-actionsByFolioIdMove-all-chargesPut',
				action: 'Move all folio charges',
				description: 'Move all charges and transitory charges from one folio to another',
			},
			{
				name: 'Move Folio Charges',
				value: 'FinanceFolio-actionsByFolioIdMove-chargesPut',
				action: 'Move folio charges',
				description: 'Move multiple charges, allowances and transitory charges from one folio to another',
			},
			{
				name: 'Move Folio Payments',
				value: 'FinanceFolio-actionsByFolioIdMove-paymentsPut',
				action: 'Move folio payments',
				description: 'Move multiple payments from one guest/booking folio to another',
			},
			{
				name: 'Post Folio Charges',
				value: 'FinanceFolio-actionsByFolioIdPost-chargesPut',
				action: 'Post folio charges',
				description: 'Posts all unposted charges for the whole length of stay',
			},
			{
				name: 'Reopen Folio',
				value: 'FinanceFolio-actionsByFolioIdReopenPut',
				action: 'Reopen folio',
				description: 'Reopens a folio',
			},
			{
				name: 'Split Folio Charge',
				value: 'FinanceFolio-actionsByFolioIdChargesByChargeIdSplitPost',
				action: 'Split folio charge',
				description: 'Splits a charge into two using the percent or amount provided Creates an allowance and two new charges',
			},
			{
				name: 'Split Folio Payment',
				value: 'FinanceFolio-actionsByFolioIdPaymentsByPaymentIdSplitPost',
				action: 'Split folio payment',
				description: 'Splits a payment into two using the percent or amount provided Creates a refund and two new payments',
			},
		],
		default: 'FinanceFolio-actionsBulk-movePut',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['finance-v1'], resource: ['FolioPayments'] } },
		options: [
			{
				name: 'Cancel Payment',
				value: 'FinanceFoliosByFolioIdPaymentsByPaymentIdCancelPut',
				action: 'Cancel payment',
				description: 'Cancels a pending payment link',
			},
			{
				name: 'Create Account Payment',
				value: 'FinanceFoliosByFolioIdPaymentsBy-payment-accountPost',
				action: 'Create account payment',
				description: 'Trigger a payment using the payment account stored on the reservation',
			},
			{
				name: 'Create Auth Payment',
				value: 'FinanceFoliosByFolioIdPaymentsBy-authorizationPost',
				action: 'Create auth payment',
				description: 'Captures a specific amount from a pre-authorization and posts it to the folio',
			},
			{
				name: 'Create Folio Payment',
				value: 'FinanceFoliosByFolioIdPaymentsPost',
				action: 'Create folio payment',
				description: 'Trigger a custom payment for the folio',
			},
			{
				name: 'Create Folio Refund',
				value: 'FinanceFoliosByFolioIdRefundsPost',
				action: 'Create folio refund',
				description: 'Trigger a refund for the folio',
			},
			{
				name: 'Create Payment Link',
				value: 'FinanceFoliosByFolioIdPaymentsBy-linkPost',
				action: 'Create payment link',
				description: 'Creates a link to a payment form where guests can pay',
			},
			{
				name: 'Create Payment Refund',
				value: 'FinanceFoliosByFolioIdPaymentsByPaymentIdRefundsPost',
				action: 'Create payment refund',
				description: 'Trigger a refund for a specific payment',
			},
			{
				name: 'Create Terminal Payment',
				value: 'FinanceFoliosByFolioIdPaymentsBy-terminalPost',
				action: 'Create terminal payment',
				description: 'Trigger a payment on a card terminal for the folio',
			},
			{
				name: 'Get Folio Payment',
				value: 'FinanceFoliosByFolioIdPaymentsByPaymentIdGet',
				action: 'Get folio payment',
				description: 'Get a payment by ID',
			},
			{
				name: 'Get Folio Refund',
				value: 'FinanceFoliosByFolioIdRefundsByRefundIdGet',
				action: 'Get folio refund',
				description: 'Get a refund by ID',
			},
			{
				name: 'List Folio Payments',
				value: 'FinanceFoliosByFolioIdPaymentsGet',
				action: 'List folio payments',
				description: 'Get a list of payments',
			},
			{
				name: 'List Folio Refunds',
				value: 'FinanceFoliosByFolioIdRefundsGet',
				action: 'List folio refunds',
				description: 'Get a list of refunds',
			},
		],
		default: 'FinanceFoliosByFolioIdPaymentsByPaymentIdCancelPut',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['finance-v1'], resource: ['Invoice'] } },
		options: [
			{
				name: 'Create Invoice',
				value: 'FinanceInvoicesPost',
				action: 'Create invoice',
				description: 'Creates an invoice for one specific folio',
			},
			{
				name: 'Get Invoice',
				value: 'FinanceInvoicesByIdGet',
				action: 'Get invoice',
				description: 'Gets invoice data',
			},
			{
				name: 'Get Invoice Pdf',
				value: 'FinanceInvoicesByIdPdfGet',
				action: 'Get invoice pdf',
				description: 'Gets an invoice PDF file',
			},
			{
				name: 'List Invoice Preview',
				value: 'FinanceInvoicesPreviewGet',
				action: 'List invoice preview',
				description: 'Gets an invoice preview for one specific folio',
			},
			{
				name: 'List Invoice Preview Pdf',
				value: 'FinanceInvoicesPreview-pdfGet',
				action: 'List invoice preview pdf',
				description: 'Gets a preview invoice PDF for one specific folio',
			},
			{
				name: 'List Invoices',
				value: 'FinanceInvoicesGet',
				action: 'List invoices',
				description: 'Gets the list of all invoices (the metadata only, not the files)',
			},
		],
		default: 'FinanceInvoicesPost',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['finance-v1'], resource: ['InvoiceAction'] } },
		options: [
			{
				name: 'Cancel Invoice',
				value: 'FinanceInvoice-actionsByIdCancelPut',
				action: 'Cancel invoice',
				description: 'Cancels an invoice',
			},
			{
				name: 'Pay Invoice',
				value: 'FinanceInvoice-actionsByIdPayPut',
				action: 'Pay invoice',
				description: 'Marks an invoice as paid',
			},
		],
		default: 'FinanceInvoice-actionsByIdCancelPut',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['finance-v1'], resource: ['SubLedger'] } },
		options: [
			{
				name: 'Export Accounts',
				value: 'FinanceAccountsExportPost',
				action: 'Export accounts',
				description: 'Returns transactions filtered by timestamp for a property for a given period',
			},
			{
				name: 'Export Accounts Daily',
				value: 'FinanceAccountsExport-dailyPost',
				action: 'Export accounts daily',
				description: 'Returns transactions filtered by date (business day) for a property for a given period',
			},
			{
				name: 'Export Accounts Gross',
				value: 'FinanceAccountsExport-gross-dailyPost',
				action: 'Export accounts gross',
				description: 'Returns gross transactions filtered by date (business day) for a property for a given period',
			},
			{
				name: 'Get Account Aggregate',
				value: 'FinanceAccountsAggregate-dailyPost',
				action: 'Get account aggregate',
				description: 'Aggregates transactions by date (business day) for all accounts and a given period',
			},
			{
				name: 'Get Account Aggregate Pairs',
				value: 'FinanceAccountsAggregate-pairs-dailyPost',
				action: 'Get account aggregate pairs',
				description: 'Aggregates transactions pairs by date (business day) for all accounts and a given period',
			},
			{
				name: 'Get Account By Number',
				value: 'FinanceAccountsByNumberGet',
				action: 'Get account by number',
				description: 'Returns one account',
			},
			{
				name: 'Get Accounts Aggregate',
				value: 'FinanceAccountsAggregatePost',
				action: 'Get accounts aggregate',
				description: 'Aggregates transactions by timestamp for all accounts and a given period',
			},
			{
				name: 'List Account Schema',
				value: 'FinanceAccountsSchemaGet',
				action: 'List account schema',
				description: 'Returns the chart of accounts of the subledger',
			},
			{
				name: 'List Child Accounts',
				value: 'FinanceAccountsChild-accountsGet',
				action: 'List child accounts',
				description: 'Returns a list of child accounts for a specified parent account',
			},
			{
				name: 'List External Accounts',
				value: 'FinanceExternal-accountsGet',
				action: 'List external accounts',
				description: 'Returns a list of external accounts',
			},
			{
				name: 'List Global Accounts',
				value: 'FinanceGlobal-accountsGet',
				action: 'List global accounts',
				description: 'Returns a list of global accounts',
			},
			{
				name: 'List Guest Accounts',
				value: 'FinanceGuest-accountsGet',
				action: 'List guest accounts',
				description: 'Returns a list of guest accounts',
			},
		],
		default: 'FinanceAccountsExportPost',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['finance-v1'], resource: ['Types'] } },
		options: [
			{
				name: 'List Currencies',
				value: 'FinanceTypesCurrenciesGet',
				action: 'List currencies',
				description: 'Returns a list of all currencies',
			},
			{
				name: 'List Payment Methods',
				value: 'FinanceTypesPayment-methodsGet',
				action: 'List payment methods',
				description: 'Returns a list of all supported payment methods',
			},
			{
				name: 'List Service Types',
				value: 'FinanceTypesService-typesGet',
				action: 'List service types',
				description: 'Returns a list of all supported service types',
			},
			{
				name: 'List Vat Types',
				value: 'FinanceTypesVatGet',
				action: 'List vat types',
				description: 'Returns a list of all VAT types',
			},
		],
		default: 'FinanceTypesCurrenciesGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['inventory-v1'], resource: ['Property'] } },
		options: [
			{
				name: 'Create Property',
				value: 'InventoryPropertiesPost',
				action: 'Create property',
				description: 'Creates a property',
			},
			{
				name: 'Get Property',
				value: 'InventoryPropertiesByIdGet',
				action: 'Get property',
				description: 'Get a property',
			},
			{
				name: 'List Properties',
				value: 'InventoryPropertiesGet',
				action: 'List properties',
				description: 'Get a properties list',
			},
			{
				name: 'Update Property',
				value: 'InventoryPropertiesByIdPatch',
				action: 'Update property',
				description: 'Allows to modify property',
			},
		],
		default: 'InventoryPropertiesPost',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['inventory-v1'], resource: ['Unit'] } },
		options: [
			{
				name: 'Check Unit Exists',
				value: 'InventoryUnitsByIdHead',
				action: 'Check unit exists',
				description: 'Check if a unit exists',
			},
			{
				name: 'Count Units',
				value: 'InventoryUnits$countGet',
				action: 'Count units',
				description: 'Returns number of units',
			},
			{
				name: 'Create Multiple Units',
				value: 'InventoryUnitsBulkPost',
				action: 'Create multiple units',
			},
			{
				name: 'Create Unit',
				value: 'InventoryUnitsPost',
				action: 'Create unit',
				description: 'Create a unit',
			},
			{
				name: 'Delete Unit',
				value: 'InventoryUnitsByIdDelete',
				action: 'Delete unit',
				description: 'Delete a unit',
			},
			{
				name: 'Get Unit',
				value: 'InventoryUnitsByIdGet',
				action: 'Get unit',
				description: 'Get a unit',
			},
			{
				name: 'List Units',
				value: 'InventoryUnitsGet',
				action: 'List units',
				description: 'Get a units list',
			},
			{
				name: 'Update Multiple Units',
				value: 'InventoryUnitsPatch',
				action: 'Update multiple units',
				description: 'Allows to patch one or more units',
			},
			{
				name: 'Update Unit',
				value: 'InventoryUnitsByIdPatch',
				action: 'Update unit',
				description: 'Allows to patch unit',
			},
		],
		default: 'InventoryUnitsByIdHead',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['inventory-v1'], resource: ['UnitAttribute'] } },
		options: [
			{
				name: 'Check Unit Attribute Exists',
				value: 'InventoryUnit-attributesByIdHead',
				action: 'Check unit attribute exists',
				description: 'Check if a unit attribute exists',
			},
			{
				name: 'Create Unit Attribute',
				value: 'InventoryUnit-attributesPost',
				action: 'Create unit attribute',
				description: 'Create a unit attribute',
			},
			{
				name: 'Get Unit Attribute',
				value: 'InventoryUnit-attributesByIdGet',
				action: 'Get unit attribute',
				description: 'Get unit attribute by id',
			},
			{
				name: 'List Unit Attributes',
				value: 'InventoryUnit-attributesGet',
				action: 'List unit attributes',
				description: 'Get unit attribute list',
			},
			{
				name: 'Update Unit Attribute',
				value: 'InventoryUnit-attributesByIdPatch',
				action: 'Update unit attribute',
				description: 'Allows to modify unit attribute',
			},
		],
		default: 'InventoryUnit-attributesByIdHead',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['inventory-v1'], resource: ['UnitGroup'] } },
		options: [
			{
				name: 'Check Unit Group Exists',
				value: 'InventoryUnit-groupsByIdHead',
				action: 'Check unit group exists',
				description: 'Check if a unit group exists',
			},
			{
				name: 'Count Unit Groups',
				value: 'InventoryUnit-groups$countGet',
				action: 'Count unit groups',
				description: 'Returns number of unit groups',
			},
			{
				name: 'Create Unit Group',
				value: 'InventoryUnit-groupsPost',
				action: 'Create unit group',
				description: 'Create a unit group',
			},
			{
				name: 'Get Unit Group',
				value: 'InventoryUnit-groupsByIdGet',
				action: 'Get unit group',
				description: 'Get a unit group',
			},
			{
				name: 'List Unit Groups',
				value: 'InventoryUnit-groupsGet',
				action: 'List unit groups',
				description: 'Get all unit groups, or all unit groups for a property',
			},
			{
				name: 'Update Unit Group',
				value: 'InventoryUnit-groupsByIdPut',
				action: 'Update unit group',
				description: 'Replace a unit group',
			},
		],
		default: 'InventoryUnit-groupsByIdHead',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['logs-v1'], resource: ['BookingLogs'] } },
		options: [
			{
				name: 'List Reservation Logs',
				value: 'LogsBookingReservationGet',
				action: 'List reservation logs',
				description: 'Returns reservation change log entries sorted by the timestamp',
			},
		],
		default: 'LogsBookingReservationGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['logs-v1'], resource: ['FinanceLogs'] } },
		options: [
			{
				name: 'List Folio Logs',
				value: 'LogsFinanceFolioGet',
				action: 'List folio logs',
				description: 'Returns folio change log entries sorted by the timestamp',
			},
			{
				name: 'List Night Audit Logs',
				value: 'LogsFinanceNight-auditGet',
				action: 'List night audit logs',
				description: 'Returns the night audit logs',
			},
			{
				name: 'List Transaction Export Logs',
				value: 'LogsFinanceTransactions-exportGet',
				action: 'List transaction export logs',
				description: 'Returns the audit log for all accounting exports that have been done',
			},
		],
		default: 'LogsFinanceFolioGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['operations-v1'], resource: ['Maintenance'] } },
		options: [
			{
				name: 'Check Maintenance Exists',
				value: 'OperationsMaintenancesByIdHead',
				action: 'Check maintenance exists',
				description: 'Check if a maintenance exists',
			},
			{
				name: 'Count Maintenances',
				value: 'OperationsMaintenances$countGet',
				action: 'Count maintenances',
				description: 'Returns number of maintenances',
			},
			{
				name: 'Create Maintenance',
				value: 'OperationsMaintenancesPost',
				action: 'Create maintenance',
				description: 'Create a new maintenance window',
			},
			{
				name: 'Create Multiple Maintenances',
				value: 'OperationsMaintenancesBulkPost',
				action: 'Create multiple maintenances',
			},
			{
				name: 'Delete Maintenance',
				value: 'OperationsMaintenancesByIdDelete',
				action: 'Delete maintenance',
				description: 'Delete a maintenance',
			},
			{
				name: 'Get Maintenance',
				value: 'OperationsMaintenancesByIdGet',
				action: 'Get maintenance',
				description: 'Get a specific maintenance',
			},
			{
				name: 'List Maintenances',
				value: 'OperationsMaintenancesGet',
				action: 'List maintenances',
				description: 'Get list of maintenances',
			},
			{
				name: 'Update Maintenance',
				value: 'OperationsMaintenancesByIdPatch',
				action: 'Update maintenance',
				description: 'Modify a maintenance',
			},
		],
		default: 'OperationsMaintenancesByIdHead',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['operations-v1'], resource: ['Operations'] } },
		options: [
			{
				name: 'Run Night Audit',
				value: 'OperationsNight-auditPut',
				action: 'Run night audit',
				description: 'Performs the night audit for one property',
			},
			{
				name: 'Update Units Condition',
				value: 'OperationsUnits-conditionPut',
				action: 'Update units condition',
				description: 'Change the condition of a unit',
			},
		],
		default: 'OperationsNight-auditPut',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['rateplan-v1'], resource: ['AgeCategory'] } },
		options: [
			{
				name: 'Create Age Category',
				value: 'SettingsAge-categoriesPost',
				action: 'Create age category',
				description: 'Create an age category',
			},
			{
				name: 'Get Age Category',
				value: 'SettingsAge-categoriesByIdGet',
				action: 'Get age category',
				description: 'Get an age category',
			},
			{
				name: 'List Age Categories',
				value: 'SettingsAge-categoriesGet',
				action: 'List age categories',
				description: 'Get an age category list',
			},
			{
				name: 'Update Age Category',
				value: 'SettingsAge-categoriesByIdPatch',
				action: 'Update age category',
				description: 'Allows to modify properties of an age category',
			},
		],
		default: 'SettingsAge-categoriesPost',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['rateplan-v1'], resource: ['CancellationPolicy'] } },
		options: [
			{
				name: 'Create Cancellation Policy',
				value: 'RateplanCancellation-policiesPost',
				action: 'Create cancellation policy',
				description: 'Create a cancellation policy',
			},
			{
				name: 'Get Cancellation Policy',
				value: 'RateplanCancellation-policiesByIdGet',
				action: 'Get cancellation policy',
				description: 'Get a specific cancellation policy',
			},
			{
				name: 'List Cancellation Policies',
				value: 'RateplanCancellation-policiesGet',
				action: 'List cancellation policies',
				description: 'Get all cancellation policies',
			},
			{
				name: 'Update Cancellation Policy',
				value: 'RateplanCancellation-policiesByIdPatch',
				action: 'Update cancellation policy',
				description: 'Allows to modify properties of a cancellation policy',
			},
		],
		default: 'RateplanCancellation-policiesPost',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['rateplan-v1'], resource: ['Company'] } },
		options: [
			{
				name: 'Create Company',
				value: 'RateplanCompaniesPost',
				action: 'Create company',
				description: 'Create a company',
			},
			{
				name: 'Get Company',
				value: 'RateplanCompaniesByIdGet',
				action: 'Get company',
				description: 'Get a company',
			},
			{
				name: 'List Companies',
				value: 'RateplanCompaniesGet',
				action: 'List companies',
				description: 'Get a list of companies',
			},
			{
				name: 'Update Company',
				value: 'RateplanCompaniesByIdPatch',
				action: 'Update company',
				description: 'Modify a company',
			},
		],
		default: 'RateplanCompaniesPost',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['rateplan-v1'], resource: ['CorporateCodes'] } },
		options: [
			{
				name: 'List Corporate Codes',
				value: 'RateplanCorporate-codesCodesGet',
				action: 'List corporate codes',
				description: 'Returns a list of corporate codes',
			},
		],
		default: 'RateplanCorporate-codesCodesGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['rateplan-v1'], resource: ['NoShowPolicy'] } },
		options: [
			{
				name: 'Create No Show Policy',
				value: 'RateplanNo-show-policiesPost',
				action: 'Create no show policy',
				description: 'Create a no-show policy',
			},
			{
				name: 'Get No Show Policy',
				value: 'RateplanNo-show-policiesByIdGet',
				action: 'Get no show policy',
				description: 'Get a specific no-show policy',
			},
			{
				name: 'List No Show Policies',
				value: 'RateplanNo-show-policiesGet',
				action: 'List no show policies',
				description: 'Get all no-show policies',
			},
			{
				name: 'Update No Show Policy',
				value: 'RateplanNo-show-policiesByIdPatch',
				action: 'Update no show policy',
				description: 'Allows to modify properties of a no-show policy',
			},
		],
		default: 'RateplanNo-show-policiesPost',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['rateplan-v1'], resource: ['PromoCodes'] } },
		options: [
			{
				name: 'List Promo Codes',
				value: 'RateplanPromo-codesCodesGet',
				action: 'List promo codes',
				description: 'Returns a list of promo codes',
			},
		],
		default: 'RateplanPromo-codesCodesGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['rateplan-v1'], resource: ['Rate'] } },
		options: [
			{
				name: 'Get Rates',
				value: 'RateplanRate-plansByIdRatesGet',
				action: 'Get rates',
				description: 'Returns a list of rates',
			},
			{
				name: 'Update Multiple Rates',
				value: 'RateplanRatesPatch',
				action: 'Update multiple rates',
				description: 'Allows to patch the rates of multiple rate plans',
			},
			{
				name: 'Update Rates',
				value: 'RateplanRate-plansByIdRatesPut',
				action: 'Update rates',
				description: 'Initializes and changes the rates for the rate plan',
			},
		],
		default: 'RateplanRate-plansByIdRatesGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['rateplan-v1'], resource: ['RatePlan'] } },
		options: [
			{
				name: 'Create Rate Plan',
				value: 'RateplanRate-plansPost',
				action: 'Create rate plan',
				description: 'Create a rate plan',
			},
			{
				name: 'Get Rate Plan',
				value: 'RateplanRate-plansByIdGet',
				action: 'Get rate plan',
				description: 'Get a rate plan',
			},
			{
				name: 'List Rate Plans',
				value: 'RateplanRate-plansGet',
				action: 'List rate plans',
				description: 'Get a rate plan list',
			},
			{
				name: 'Update Multiple Rate Plans',
				value: 'RateplanRate-plansPatch',
				action: 'Update multiple rate plans',
				description: 'Allows to patch one or more rate plans',
			},
			{
				name: 'Update Rate Plan',
				value: 'RateplanRate-plansByIdPut',
				action: 'Update rate plan',
				description: 'Replace a rate plan',
			},
		],
		default: 'RateplanRate-plansPost',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['rateplan-v1'], resource: ['Service'] } },
		options: [
			{
				name: 'Create Service',
				value: 'RateplanServicesPost',
				action: 'Create service',
				description: 'Create a service',
			},
			{
				name: 'Get Service',
				value: 'RateplanServicesByIdGet',
				action: 'Get service',
				description: 'Get a specific service',
			},
			{
				name: 'List Services',
				value: 'RateplanServicesGet',
				action: 'List services',
				description: 'Get all services',
			},
			{
				name: 'Update Service',
				value: 'RateplanServicesByIdPatch',
				action: 'Update service',
				description: 'Modify a service',
			},
		],
		default: 'RateplanServicesPost',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['reports-v1'], resource: ['Reports'] } },
		options: [
			{
				name: 'List Arrivals Report',
				value: 'ReportsReportsArrivalsGet',
				action: 'List arrivals report',
				description: 'Returns the number of arrivals in a month for a property',
			},
			{
				name: 'List Company Invoices Vat Report',
				value: 'ReportsReportsCompany-invoices-vatGet',
				action: 'List company invoices vat report',
				description:
					'Returns the list of company invoices with information on the company and the VAT breakdown',
			},
			{
				name: 'List Ordered Services Report',
				value: 'ReportsReportsOrdered-servicesGet',
				action: 'List ordered services report',
				description: 'List of ordered services',
			},
			{
				name: 'List Property Performance Report',
				value: 'ReportsReportsProperty-performanceGet',
				action: 'List property performance report',
				description: 'Returns the property performance report which includes the ADR and the RevPAR for each business day',
			},
			{
				name: 'List Revenues Report',
				value: 'ReportsReportsRevenuesGet',
				action: 'List revenues report',
				description: 'Returns the revenues report for a property',
			},
		],
		default: 'ReportsReportsArrivalsGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['settings-v1'], resource: ['CapturePolicies'] } },
		options: [
			{
				name: 'Get Capture Policy',
				value: 'SettingsCapture-policiesByIdGet',
				action: 'Get capture policy',
				description: 'Get a specific capture policy',
			},
			{
				name: 'List Capture Policies',
				value: 'SettingsCapture-policiesGet',
				action: 'List capture policies',
				description: 'Get all capture policies',
			},
			{
				name: 'Update Capture Policy',
				value: 'SettingsCapture-policiesByIdPatch',
				action: 'Update capture policy',
				description: 'Allows to modify properties of a capture policy',
			},
		],
		default: 'SettingsCapture-policiesByIdGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['settings-v1'], resource: ['CityTax'] } },
		options: [
			{
				name: 'Create City Tax',
				value: 'SettingsCity-taxPost',
				action: 'Create city tax',
				description: 'Create a city tax',
			},
			{
				name: 'Get City Tax',
				value: 'SettingsCity-taxByIdGet',
				action: 'Get city tax',
				description: 'Get a specific city tax',
			},
			{
				name: 'List City Taxes',
				value: 'SettingsCity-taxGet',
				action: 'List city taxes',
				description: 'Get all city taxes',
			},
			{
				name: 'Update City Tax',
				value: 'SettingsCity-taxByIdPatch',
				action: 'Update city tax',
				description: 'Allows to modify city tax',
			},
		],
		default: 'SettingsCity-taxPost',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['settings-v1'], resource: ['CustomSubAccounts'] } },
		options: [
			{
				name: 'Check Sub Account Exists',
				value: 'SettingsSub-accountsByIdHead',
				action: 'Check sub account exists',
				description: 'Check if the sub-account exists',
			},
			{
				name: 'Count Sub Accounts',
				value: 'SettingsSub-accounts$countGet',
				action: 'Count sub accounts',
				description: 'Returns number of sub-accounts',
			},
			{
				name: 'Create Sub Account',
				value: 'SettingsSub-accountsPost',
				action: 'Create sub account',
				description: 'Create a sub-account',
			},
			{
				name: 'Get Sub Account',
				value: 'SettingsSub-accountsByIdGet',
				action: 'Get sub account',
				description: 'Returns one sub-account',
			},
			{
				name: 'List Sub Accounts',
				value: 'SettingsSub-accountsGet',
				action: 'List sub accounts',
				description: 'Returns a list of all sub-accounts',
			},
			{
				name: 'Update Sub Account',
				value: 'SettingsSub-accountsByIdPatch',
				action: 'Update sub account',
				description: 'Allows to modify the name of the sub-account',
			},
		],
		default: 'SettingsSub-accountsByIdHead',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['settings-v1'], resource: ['FeatureSettings'] } },
		options: [
			{
				name: 'Get Feature Settings',
				value: 'SettingsFeaturesByPropertyIdGet',
				action: 'Get feature settings',
				description: 'Get feature settings for a property',
			},
			{
				name: 'Update Feature Settings',
				value: 'SettingsFeaturesByPropertyIdPatch',
				action: 'Update feature settings',
				description: 'Allows to modify feature settings',
			},
		],
		default: 'SettingsFeaturesByPropertyIdGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['settings-v1'], resource: ['InvoiceAddress'] } },
		options: [
			{
				name: 'List Invoice Addresses',
				value: 'SettingsInvoice-addressGet',
				action: 'List invoice addresses',
				description: 'Get invoice addresses',
			},
			{
				name: 'Patch Invoice Addresses',
				value: 'SettingsInvoice-addressPatch',
				action: 'Patch invoice addresses',
				description: 'Change fields in the invoice address of one or more properties',
			},
			{
				name: 'Update Invoice Addresses',
				value: 'SettingsInvoice-addressPut',
				action: 'Update invoice addresses',
				description: 'Create or update invoice addresses for one or more properties',
			},
		],
		default: 'SettingsInvoice-addressGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['settings-v1'], resource: ['Languages'] } },
		options: [
			{
				name: 'List Language Settings',
				value: 'SettingsLanguagesGet',
				action: 'List language settings',
				description: 'Get the language settings for the account',
			},
			{
				name: 'Update Language Settings',
				value: 'SettingsLanguagesPut',
				action: 'Update language settings',
				description: 'Replaces the language settings for the account',
			},
		],
		default: 'SettingsLanguagesGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['settings-v1'], resource: ['MarketSegment'] } },
		options: [
			{
				name: 'Check Market Segment Exists',
				value: 'SettingsMarket-segmentsByIdHead',
				action: 'Check market segment exists',
				description: 'Check if a market segment exists',
			},
			{
				name: 'Count Market Segments',
				value: 'SettingsMarket-segments$countGet',
				action: 'Count market segments',
				description: 'Returns number of market segments',
			},
			{
				name: 'Create Market Segment',
				value: 'SettingsMarket-segmentsPost',
				action: 'Create market segment',
				description: 'Create a market segment',
			},
			{
				name: 'Get Market Segment',
				value: 'SettingsMarket-segmentsByIdGet',
				action: 'Get market segment',
				description: 'Get a market segment',
			},
			{
				name: 'List Market Segments',
				value: 'SettingsMarket-segmentsGet',
				action: 'List market segments',
				description: 'Returns a list of all market segments, filtered by the specified parameters',
			},
			{
				name: 'Update Market Segment',
				value: 'SettingsMarket-segmentsByIdPatch',
				action: 'Update market segment',
				description: 'Allows to modify market segment',
			},
		],
		default: 'SettingsMarket-segmentsByIdHead',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['settings-v1'], resource: ['PropertySettings'] } },
		options: [
			{
				name: 'Get Property Settings',
				value: 'SettingsPropertiesByIdGet',
				action: 'Get property settings',
			},
		],
		default: 'SettingsPropertiesByIdGet',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['settings-v1'], resource: ['TimeSliceDefinitions'] } },
		options: [
			{
				name: 'Create Time Slice Definition',
				value: 'SettingsPropertiesByPropertyIdTime-slice-definitionsPost',
				action: 'Create time slice definition',
				description: 'Creates a time slice definition',
			},
			{
				name: 'Get Time Slice Definition',
				value: 'SettingsPropertiesByPropertyIdTime-slice-definitionsByIdGet',
				action: 'Get time slice definition',
				description: 'Get a specific time slice definition',
			},
			{
				name: 'List Time Slice Definitions',
				value: 'SettingsPropertiesByPropertyIdTime-slice-definitionsGet',
				action: 'List time slice definitions',
				description: 'Get time slice definitions',
			},
			{
				name: 'Update Time Slice Definition',
				value: 'SettingsPropertiesByPropertyIdTime-slice-definitionsByIdPatch',
				action: 'Update time slice definition',
				description: 'Modifies a specific time slice definition for the property',
			},
		],
		default: 'SettingsPropertiesByPropertyIdTime-slice-definitionsPost',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['webhook-v1'], resource: ['HealthCheck'] } },
		options: [
			{
				name: 'Ping',
				value: 'PingerPost',
				action: 'Ping',
				description: 'Health check endpoint',
			},
		],
		default: 'PingerPost',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { group: ['webhook-v1'], resource: ['Subscriptions'] } },
		options: [
			{
				name: 'Create Subscription',
				value: 'SubscriptionsPost',
				action: 'Create subscription',
				description: 'Creates subscription',
			},
			{
				name: 'Delete Subscription',
				value: 'SubscriptionsByIdDelete',
				action: 'Delete subscription',
				description: 'Deletes subscription',
			},
			{
				name: 'Get Subscription',
				value: 'SubscriptionsByIdGet',
				action: 'Get subscription',
				description: 'Get a subscription',
			},
			{
				name: 'List Subscriptions',
				value: 'SubscriptionsGet',
				action: 'List subscriptions',
				description: 'Get all subscriptions created for the current account and client',
			},
			{
				name: 'Update Subscription',
				value: 'SubscriptionsByIdPut',
				action: 'Update subscription',
				description: 'Updates subscription',
			},
		],
		default: 'SubscriptionsPost',
	},
];
